### PR TITLE
Defender on map

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR fixes the perspective and shadow issues of the _Defender_ animation on the map. It also improves the related map.

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@by003, in the [background](https://github.com/vcmi-mods/highlands-town/blob/vcmi-1.5/content/Data/highlands/town-screen/TPFGBACK.bmp), the centered mountain is half transparent. Should it be fully removed or fully opaque?

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, correct me if I'm wrong: [those files](https://github.com/vcmi-mods/highlands-town/blob/vcmi-1.6/content/Sprites/highlands/town-screen/buildings/lv07-1.bmp) should not be here?

`https://github.com/vcmi-mods/highlands-town/blob/vcmi-1.6/content/Sprites/highlands/town-screen/buildings/lv07-[1-18].bmp`

**Comment by misiokles** [comment]
I don't know :) It's not my mod. Something doesn't work?

**Comment by Fabrice-TIERCELIN** [comment]
Everything works. I will clean it the day I will do a contrib on this mod.

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, I plan to create a mod that is a pack of all the creatures in _New land town_ as neutral creatures except those ones we already have and the ugly ones. This way, we don't have to support the towns but we will benefit of the creatures.

If you agree, can you create the mod?

**Comment by misiokles** [comment]
yes, of course! What will be the name of this mod?

**Comment by Fabrice-TIERCELIN** [comment]
_Land of New Town Creatures_

**Comment by misiokles** [comment]
Done.

**Comment by Fabrice-TIERCELIN** [comment]
I think that you can delete [this new repository](https://github.com/vcmi-mods/land-of-new-town-creatures) because I see that all the creature mods have been packed into [a single meta-mod](https://github.com/vcmi-mods/new-monsters-pack/tree/vcmi-1.6) (I don't see the point) so let's add this into it also.

**Pull request merged**
