### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR translates the mod into French, cleans the useless files, improves the map and updates the first screenshot.

I have used this page for translation before proofreading:
https://translate.google.com/?sl=en&tl=fr&text=Berserker&op=translate

I have installed [_Custom Javascript for WebSite 2_](https://chromewebstore.google.com/detail/custom-javascript-for-web/ddbjnfjiigjmcpcpkmhogomapikjbjdk) and written the following script:

```JavaScript
// Creation
let fileTextarea = document.createElement('textarea');
let brElement1 = document.createElement('br');
let regExInput = document.createElement('input');
let runButton = document.createElement('button');
let brElement2 = document.createElement('br');
let resultTextarea = document.createElement('textarea');

fileTextarea.rows = 10;
fileTextarea.cols = 200;
resultTextarea.rows = 10;
resultTextarea.cols = 200;
regExInput.value = "(?<=\\\"\\ \\:\\ \\\")((?:[^\\\\\\\"]|\\\\.)*)(?=\\\"\\r?\\n?[,\\}])";
regExInput.size = 100;
runButton.innerText = 'Translate inner text';
let fileText;
let regExString;
let splitText;
let resultStrings;
let i;
let oneString;
runButton.onclick = () => {
  fileText = fileTextarea.value;
  regExString = new RegExp(regExInput.value, "g");
  splitText = fileText.split(regExString);
  resultStrings = [];
  i = 0;
  iteration();
};

function iteration() {
  if (i < splitText.length) {
    oneString = splitText[i];
    if ((i % 2) == 1) {
      let tradTextarea = document.getElementsByTagName('textarea')[0];
      tradTextarea.value = oneString.replaceAll("\\\"", "\"");
      tradTextarea.focus();
      document.getElementById('K32').click();
  
      setTimeout(iterationEnd, 3 * 1000);
    } else {
      resultStrings.push(oneString);
      i++;
      iteration();
    }
  } else {
    resultTextarea.value = resultStrings.join("");
  }
}

function iterationEnd() {
  let copyButton;
  let tooltips = document.getElementsByTagName('div');
  for (let tooltip of tooltips) {
    if (tooltip.innerHTML == 'Copier la traduction') {
      copyButton = tooltip.previousSibling;
      break;
    }
  }
  copyButton.click();
  navigator.clipboard.readText().then(function(pastedContent) {
    if (pastedContent) {
      pastedContent = pastedContent.replaceAll("\"", "\\\"").replaceAll("«", "\\\"").replaceAll("»", "\\\"");
    }
    resultStrings.push(pastedContent);
    resultTextarea.value = resultStrings.join("");
    i++;
    iteration();
  });
}

// Layout
var bodyElement = document.getElementsByTagName('body')[0];
bodyElement.appendChild(fileTextarea);
bodyElement.appendChild(brElement1);
bodyElement.appendChild(regExInput);
bodyElement.appendChild(runButton);
bodyElement.appendChild(brElement2);
bodyElement.appendChild(resultTextarea);
```

And I have used this RegEx to remove doubles:
`(?<=\n)(\s*"([^"]*)" : "[^\r\n]*\r?\n(?:.*\r?\n)*)\s*"\2" : "[^\r\n]*\r?\n`
`$1`

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, it seems that this PR makes _VCMI_ fail at startup. I don't know why. I suggest to revert and readd each features one by one.

**Comment by misiokles** [comment]
Cannot confirm.

**Comment by Fabrice-TIERCELIN** [comment]
But can revert 🙂

**Comment by Fabrice-TIERCELIN** [comment]
revert+cleanup is failing

**Comment by Fabrice-TIERCELIN** [comment]
It works again! I think you can restore, @misiokles

**Comment by misiokles** [comment]
It worked all the time.

**Pull request merged**
